name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Build Step
      - name: Build Application
        run: echo "Building Application"

      # Step 3: Test Step
      - name: Run Tests
        run: echo "Running Tests"

      # Step 4: Deploy Step
      - name: Deploy Application
        run: echo "Deploying Application"
